### ISSUE TITLE
Update component to generate unique ids for mirror an textarea

### ISSUE THREAD

**Issue by userquin** [PolymerElements/iron-autogrow-textarea#115]
Components like paper-input-behavior and paper-input have been recently updated to assign a unique id to its inputs, but iron-autogrow-textarea still uses hardcoded ids for mirror and textarea:

```html
<div id="mirror"

<textarea id="textarea"...
```
and should be:

```html
<div id$="[[_mirrorId]]"...
<textarea id$="[[_inputId]]"
```
```javascript
properties: {
        _inputId: {
          type: String,
          value: ''
      },

        _mirrorId: {
          type: String,
          value: ''
        }
}
...
...
      _generateInputId: function() {
        if (!this._inputId || this._inputId === '') {
          this._inputId =  'input-' + Polymer.PaperInputHelper.NextInputID++;
        }
      },

      _generateMirrorId: function() {
        if (!this._mirrorId || this._mirrorId === '') {
          this._mirrorId =  'mirror-' + Polymer.PaperInputHelper.NextInputID++;
        }
      },
...
    get textarea() {
        if (!this.$) {
          this.$ = {}
        }
        if (!this.$.textarea) {
          this._generateInputId();
          this.$.textarea = this.$$('#' + this._inputId);
        }
      return this.$.textarea;
    },

    get mirror() {
        if (!this.$) {
          this.$ = {}
        }
        if (!this.$.mirror) {
          this._generateMirrorId();
          this.$.mirror = this.$$('#' + this._mirrorId);
        }
      return this.$.mirror;
    },
```
and finally replacing all 
```javacript
this.$.textarea
this.$.mirror
````
with
```javacript
this.textarea
this.mirror
````

**Comment by notwaldorf** [comment]
Paper-input was changed because Chrome started reporting as errors if inputs with type=password had duplicate IDs, which happens in shady DOM. Since this cannot happen with textareas, we don’t need to do this. 

Elements should be assumed as being written with a shadow DOM: the fact that in shady dom you get duplicate IDs like this is fine, and shouldn’t cause problems (you’re definitely not supposed to query select across shadow boundaries)

**Comment by notwaldorf** [comment]
Closing, since I don't think we need to fix this, but please re-open if something doesn't work or you get any console errors on this topic :)

**Comment by userquin** [comment]
problems come with polymer 1.0 with shady polyfill and ay11 (firefox, safari...)

**Comment by notwaldorf** [comment]
Not sure I understand. Do you mean in general, or particular to the unique IDs? If so, do you have repro steps?

**Comment by userquin** [comment]
I have not tested it yet, the problem was with paper-input type password, this.$$('paper-input<some selector>') did not work returning always null.
I have to test with a page containing 2 paper-textarea and check if this.$$('paper-textarea<some selector>') works...
