### ISSUE TITLE
Textarea should support onblur event

### ISSUE THREAD

**Issue by wq9** [PolymerElements/iron-autogrow-textarea#13]
Is there a way to have onblur event? For example:
```html
<iron-autogrow-textarea class="paper-input-input" value="{{value::blur}}"></iron-autogrow-textarea>
```

**Comment by wq9** [comment]
Also, autofocus should be Boolean:
```
      autofocus: {
        type: Boolean,
        value: false
      },
```

**Comment by notwaldorf** [comment]
Blur as an event is already supported: http://jsbin.com/garequ/edit?html,output

The `::` notation is used for two way binding to native elements (like `<textarea>`). `iron-autogrow-textarea` isn't a native element, so that shouldn't work
