### ISSUE TITLE
iOS 13 has non standard margin left fixes

### ISSUE THREAD

**Issue by rubenstolk** [PolymerElements/iron-autogrow-textarea#133]
@notwaldorf can you please change L286 to: ```var IS_IOS = navigator.userAgent.match(/iP(?:[oa]d|hone)/) && !navigator.userAgent.match(/OS 1[3456789]/);``` for the `1.x` release, iOS has solved this issue from v13 onwards...

**Comment by rubenstolk** [comment]
plz... @notwaldorf

**Comment by notwaldorf** [comment]
Sorry, I haven't worked on this project in over 2 years, so I'm not sure
what the status of this repo is.
