### ISSUE TITLE
Documentation and behaviour disagree

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/iron-autogrow-textarea#24]
The documentation calls for `update()` to be called, whereas the function is [only available as `_update()`](https://github.com/PolymerElements/iron-autogrow-textarea/blob/master/iron-autogrow-textarea.html#L246-L254) in the source.

Either `update()` is missing, or the docs need to be updated.

**Comment by notwaldorf** [comment]
@tigerhawkvok I may be missing it, but I don't see where the documentation calls for `update()` to be called. Can you link in the line, please?

**Comment by tigerhawkvok** [comment]
It's not documented at all on [the elements page](https://elements.polymer-project.org/elements/iron-autogrow-textarea) (which is arguably a different issue), but [it is on the README.md](https://github.com/PolymerElements/iron-autogrow-textarea/blob/1689201255c5844a2b4b3ed5f3ee34db047ecc57/README.md):

![image](https://cloud.githubusercontent.com/assets/165937/8915217/82172848-3458-11e5-924b-11c347abc34a.png)

So, on [line 15](https://github.com/PolymerElements/iron-autogrow-textarea/blame/1689201255c5844a2b4b3ed5f3ee34db047ecc57/README.md#L15) and [line 24](https://github.com/PolymerElements/iron-autogrow-textarea/blame/1689201255c5844a2b4b3ed5f3ee34db047ecc57/README.md#L24)

**Comment by notwaldorf** [comment]
Ah, the `README` has fallen behind the real world. Sorry about that, fixing now :)

**Comment by notwaldorf** [comment]
This has been fixed in https://github.com/PolymerElements/iron-autogrow-textarea/pull/28
