### ISSUE TITLE
No text-cursor when editing in current firefox 39

### ISSUE THREAD

**Issue by makrolabs** [PolymerElements/iron-autogrow-textarea#27]
this problem does not occur when removing the
      Polymer.IronControlState
from the behaviours array of iron-autogrow-textarea.

**Comment by makrolabs** [comment]
This can be fixed by removing the 
      -moz-appearance: textarea;
line from the :host css style. See PR.

**Comment by makrolabs** [comment]
See the official example where it fails as well:
https://elements.polymer-project.org/elements/iron-autogrow-textarea?view=demo:demo/index.html

**Comment by juliomelo** [comment]
See PolymerElements/paper-input#110

**Comment by notwaldorf** [comment]
No longer reproducible (was fixed in an `IronControlState` PR)
