### ISSUE TITLE
safari shows a top border?

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-autogrow-textarea#36]
![image](https://cloud.githubusercontent.com/assets/863731/9776609/89626a70-575a-11e5-97f8-eff759719cf4.png)

http://brmform.appspot.com/

**Comment by notwaldorf** [comment]
`iron-autogrow-textarea` does not apply any material design styles, and looks exactly like a native `<textarea>`. If you want it to look like a `paper-input`, you need to use a `<paper-textarea>` instead.

**Comment by gertcuykens** [comment]
hold on, because i was using `paper-textarea` let me move this issue
