### ISSUE TITLE
Swipe input on stock android keyboard skips words

### ISSUE THREAD

**Issue by ZoneMR** [PolymerElements/iron-autogrow-textarea#39]
Using Chrome, Android lollipop stock keyboard. Normal typing works fine. Swiping to input words results in every other word not appearing inside iron-autogrow-textarea.

**Comment by notwaldorf** [comment]
Gah, good catch. @azakus and I did some sherlocking, and the problem is that we write back to the underlying `textarea` on every input. This isn't normally a problem, but swiping does some type-in-a-different-place-and-commit-later action that I think doesn't work with this.

I'll take a look!
