### ISSUE TITLE
_constrained() output and mirror content not compatible with xhtml

### ISSUE THREAD

**Issue by jmillikin** [PolymerElements/iron-autogrow-textarea#47]
Trying to use `<iron-autogrow-textarea>` or elements based on it (such as `<paper-textarea>`) fails in documents with an `application/xhtml+xml` mimetype. This is due to two HTML-isms:

* Use of the `&nbsp;` entity, which is not defined in XHTML mode. This can be replaced with the slightly less readable `&#160;` entity.
* Injecting code into innerHTML with `<br>`, which is an unterminated tag in XHTML. The self-terminating form is safe to use in both XHTML and HTML mode.

After applying the following diff, I am able to use `<paper-textarea>` in an XHTML-mode document:

```diff
--- iron-autogrow-textarea/iron-autogrow-textarea.html
+++ iron-autogrow-textarea/iron-autogrow-textarea.html
@@ -71,7 +71,7 @@ this element's `bind-value` instead for
   </style>
   <template>
     <!-- the mirror sizes the input/textarea so it grows with typing -->
-    <div id="mirror" class="mirror-text" aria-hidden="true">&nbsp;</div>
+    <div id="mirror" class="mirror-text" aria-hidden="true">&#160;</div>
 
     <!-- size the input/textarea with a div, because the textarea has intrinsic size in ff -->
     <div class="textarea-container fit">
@@ -300,7 +300,7 @@ this element's `bind-value` instead for
       while (this.rows > 0 && _tokens.length < this.rows) {
         _tokens.push('');
       }
-      return _tokens.join('<br>') + '&nbsp;';
+      return _tokens.join('<br/>') + '&#160;';
     },
 
     _valueForMirror: function() {
```

**Comment by notwaldorf** [comment]
I don't think we officially support XHTML, and I think changing the encoding would make it less confusing (most people know what `&nbsp;` is, I had to look up what `&#160` was. I'm also not sure how supported XHTML features will be for the HTML imports spec, on which we rely quite heavily.

Is there a reason why you're using xhtml and not html? 

/cc @azakus who knows more about this than me on the topic

**Comment by notwaldorf** [comment]
Reopening! Will fix after an offline conversation.
