### ISSUE TITLE
Doesn't initialize properly with textarea content

### ISSUE THREAD

**Issue by hadfieldn** [PolymerElements/iron-autogrow-textarea#6]
The attached() callback sets `this.bindValue` to `this.value`, which doesn't appear to be defined anywhere. As a result, bindValue gets initialized to `undefined` rather than the initial content of the textarea. This is particularly problematic because if the textarea is empty, its value should be the empty string rather than undefined.

Also, if the textarea contains initial content that exceeds its size, it won't grow to fit it until update() is called on its iron-autogrow-textarea.

I believe the simplest fix for these issues would be to change the attached() callback to simply invoke `this.update()`. I am submitting a PR with this change and with tests that illustrate the issue.

Thanks!

**Comment by morethanreal** [comment]
Should not be an issue now, because `<iron-autogrow-textarea>` now includes a built-in `<textarea>`.
