### ISSUE TITLE
max-rows doesn't work

### ISSUE THREAD

**Issue by Zippersk** [PolymerElements/iron-autogrow-textarea#68]
I test it only in chrome, but example on demo page "Scrolls after 4 rows" doesn't work for me.
https://elements.polymer-project.org/elements/iron-autogrow-textarea?view=demo:demo/index.html&active=iron-autogrow-textarea

**Comment by e111077** [comment]
Heya,

Our model works such that it begins to scroll after 4 rows delimited by newlines. Can you confirm that your rows are delimited in such a way?

**Comment by Zippersk** [comment]
My bad. It works when you have spaces between words.
![bez nazvu](https://cloud.githubusercontent.com/assets/6651236/12505342/39a70c02-c0e6-11e5-868f-a31f119c2c85.jpg)
