### ISSUE TITLE
Getting the textarea to scroll by setting an explicit height.

### ISSUE THREAD

**Issue by JockeCK** [PolymerElements/iron-autogrow-textarea#70]
"Unless an explicit height or the maxRows property is set, it will never scroll."

Could we have an demo on how to get it to scroll by setting an explicit height?

**Comment by notwaldorf** [comment]
Sure! I think this answers your question: http://jsbin.com/ziqele/edit?html,output

Please re-open if that's not the case :)

**Comment by notwaldorf** [comment]
Re-opening this, since there's actually a bug where the `mirror` div goes a big crazy in this case. See the jsbin for the repro.

**Comment by JockeCK** [comment]
Thank you for the quick and illustrative answer/bug fix.
