### ISSUE TITLE
sizing issues with version on master

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-autogrow-textarea#75]
The version in `master` has issues in sizing the internal textarea
![textarea](https://cloud.githubusercontent.com/assets/6173664/13156109/bebb993a-d635-11e5-9265-52223aefab13.gif)

**Comment by notwaldorf** [comment]
Can't repro! Can you clean your bower components maybe?

**Comment by valdrinkoshi** [comment]
it is! closing this
