### ISSUE TITLE
mixin not fully customizable

### ISSUE THREAD

**Issue by timreichen** [PolymerElements/iron-autogrow-textarea#79]
### Description
The --iron-autogrow-textarea will apply to the internal textarea. But border and width etc. are also set on :host. Therefore it is not possible to change the style for example of the border.
### Expected outcome
:host {
    --iron-autogrow-textarea {
        border 1px solid red;
    }
}
should set the border to red.
### Actual outcome
The element will have two borders (:host and textarea), black and red.
### Steps to reproduce
Copy the upper text in style-tag.

### Browsers Affected

- [x] Chrome
- [X] Firefox
- [X] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
There are several problems with your example: 1) you need a `:` after the name of the mixin, and 2) you need a `:` after the css property `border`. The correct code should be:
```
:host {
  --iron-autogrow-textarea: {
    border: 1px solid red;
  }
}
```

Here's a JSBin demoing that: http://jsbin.com/kaseyi/edit?html,output
