### ISSUE TITLE
disabling & enabling 

### ISSUE THREAD

**Issue by erinhong17** [PolymerElements/iron-autogrow-textarea#85]
**Problem:** 
I want to use a <iron-autogrow-textarea> for a section of text that I want disabled at first and to be editable at the click of a button to re-enable the editing of that text. 

**Approach:** 
Set it initially with 
`<iron-autogrow-textarea id="editable" disabled="true" placeholder="Hello!"></iron-autogrow-textarea>`

And using javascript, I'm able to reassign the disabled to "false"
`this.$.editable.disabled="false";`

Checking with print statements, I see it starts out with "true" then changes to "false" when I click my edit button. However, I cannot edit the piece of text and seems to be still disabled.

**Comment by notwaldorf** [comment]
You need to set it to `false`, the boolean (not the string). It's a boolean attribute, which while it's set, it always evaluates to true, no matter what the content is (`editable.disabled="batman"` would still keep it disabled). When you set it to `false`, the Boolean, Polymer removes that attribute for you altogether.

Here's a jsbin where this works: http://jsbin.com/kevisa/edit?html,output
